### ISSUE TITLE
Xcode 14.3 Update and Usage

### ISSUE THREAD

**Issue by jayvenn** [maxim-lobanov/setup-xcode#66]
With only the latest supported Xcode version 14.2 (GitHub runner image):
https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

Is it possible to use Xcode 14.3, and how for that case?

References:
https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

<img width="698" alt="image1" src="https://user-images.githubusercontent.com/12175043/231905797-3bb68ab3-73be-4c56-b1ab-3f56ff60abb6.png">

<img width="1158" alt="image2" src="https://user-images.githubusercontent.com/12175043/231905866-a42c6238-2e94-4b9d-b1c5-e8351aabf8f7.png">

**Comment by maxim-lobanov** [comment]
Hi @jayvenn , unfortunately, it is not possible.
This action only helps to select Xcode versions pre-installed on image. Installing Xcode on-flight is not supported because it would be take hours.

Xcode 14.3 was released on 30 Mar and it is still not added to image. From the [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes) I see `Xcode 14.3 requires a Mac running macOS Ventura 13.0 or later.`. I guess it is the reason why it is still not added to GItHub Actions images.

They only support macOS 11 and 12 right now and adding macOS 13 is tracked in this issue: https://github.com/actions/runner-images/issues/6426

As soon as macOS 13 image is added with Xcode 14.3, this action will start working properly for it.
