### ISSUE TITLE
Xcode 15.0

### ISSUE THREAD

**Issue by pronebird** [maxim-lobanov/setup-xcode#70]
GitHub is rolling out Xcode 15.0.1 across the board and today I noticed that despite YML pointing at Xcode 15.0, the setup-xcode action picks up 15.0.1 instead, which is a bit surprising. 

Does setup-xcode automatically pick the minor patch release instead of sticking to the exact version specified or do we have to specify "15.0.0" to make it understand the intent?

```
Run maxim-lobanov/setup-xcode@v1
  with:
    xcode-version: 15.0
  env:
    SOURCE_PACKAGES_PATH: .spm
Switching Xcode to version '15.0'...
Xcode is set to 15.0.1 (15A507)
```

**Comment by maxim-lobanov** [comment]
Hey 👋 ,
Yes, it is expected behavior. As it is mentioned in [Available parameters](https://github.com/maxim-lobanov/setup-xcode#available-parameters), action uses semver notation to resolve versions.
In semver notation, `15.0` means `15.0.x` and 15.0.1 satisfies this requirement.

So I think you want to use `xcode-version: '15.0.0'` to stick on Xcode 15.0.0.

Also, tiny suggestion to use quotes around version: `xcode-version: '15.0.0'` because by default GitHub parses `xcode-version: 15.0` as a number and will trim trailing `.0`. So actually, your current input works as `xcode-version: 15`. It is mentioned in readme.

**Comment by pronebird** [comment]
Hi, thanks. It makes sense.
